######################################################################
# Automatically generated by qmake (3.0) Wed Jul 24 23:16:44 2013
######################################################################

cache() 

TEMPLATE = app
TARGET = EKChat
INCLUDEPATH += .
RESOURCES += resources.qrc


QT += quick qml core gui declarative

# Input
SOURCES += src/*.cpp
HEADERS += src/*.hpp
OBJECTS_DIR = bin
MOC_DIR = moc

mac {
    CONFIG -= app_bundle
}
